### ISSUE TITLE
Implementere nytt design på kundesiden som ligger på figma

### ISSUE THREAD

**Issue by mariehessen** [knowit/folk-webapp#381]
- [ ] Filtrere på kunder. #382 
- [x] Filtrering på halvår i tillegg til måned, kvartal og år. #421
- [x] Gjør om periodefiltrering til knapper istedenfor dropdown meny. #427 
- [ ] Mulighet å angi spesifisert periode man vil filtrere på. #422 
- [ ] Oversikt over kunder som vises i grafen. Kundene vises som kort. #423 
- [x] Endre kunde kort-design. #428 
- [ ] Oversikt over øvrige kunder. Inkludert alternative sorteringmuligheter: alfabetisk, antall konsulenter, antall timer #424
- [ ] y-aksen endrer verdier og forhold alt ettersom kundene som vises. 

+++

**Comment by henrikav** [comment]
Denne burde egentlig splittes opp i flere issues
